name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript
        run: npx tsc --noEmit

      - name: Run Unit Tests
        run: npx vitest run

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start server
        run: npm run dev &
        env:
          NODE_ENV: development

      - name: Wait for server to start
        run: npx wait-on http://localhost:5173 # Adjust the port if necessary

      - name: Run E2E Tests
        run: npx playwright test

      - name: Stop server
        if: always()
        run: kill $(jobs -p)
